#!/bin/sh
# testcase v1.1(linux), Pety & Milos, 2015
# $Id: testcase 115 2015-02-25 23:33:17Z petyovsky $

# usage: ./testcase program_name test_file_name expected_exit_code
if [ $# -ne 3 ]
then
	echo "$0: param_error: Bad number of parameters"
	echo "usage:"
	echo "\t$0 <program_name> <testfile_name> <expected_exit_code>\a"
	exit 1
fi
program_name=$1
testfile_name=$2
expected_exit_code=$3

# Execute tested program and generate outputfile retargeting stdout and stderr to the .stdout file
if [ ! -x $program_name ]
then
	echo "$0: param_error: Cannot execute program: $program_name"
	exit 2
fi
if [ ! -r "$testfile_name.stdin" ]
then
	echo "$0: param_error: Cannot found readable input file: $testfile_name.stdin"
	exit 3
fi
if [ ! -r $testfile_name.stdout.ref ] && [ ! -r $testfile_name.stderr.ref ]
then
	echo "$0: internal_error: Cannot found reference file: $testfile_name.stdout.ref or $testfile_name.stderr.ref"
	exit 4
fi

$program_name < $testfile_name.stdin >$testfile_name.stdout 2>$testfile_name.stderr
program_exit_code=$?

# Executed program exit code test
if [ $program_exit_code -ne $expected_exit_code ]
then
	echo "$0: test_error: Program: $program_name <$testfile_name.stdin exit value:($program_exit_code), expected value:($expected_exit_code)"
	exit 5
fi

# Executed program stderr file test
if [ -r $testfile_name.stderr.ref ]
then
	if [ ! -r $testfile_name.stderr ]
	then
		echo "$0: test_error: Cannot found file: $testfile_name.stderr"
		exit 6
	fi
	diff --strip-trailing-cr $testfile_name.stderr $testfile_name.stderr.ref &> /dev/null
	diff_stderr_exit_code=$?
	if [ $diff_stderr_exit_code -eq 0 ]
	then
		# echo "$0: message: Testcase for stderr passed. Cool. ;-)"
		rm -f $testfile_name.stderr
	elif [ $diff_stderr_exit_code -eq 1 ]
	then
		echo "$0: test_error: Files: $testfile_name.stderr and $testfile_name.stderr.ref differ"
		exit 7
	else
		echo "$0: internal_error: There is something wrong with the diff command and files: $testfile_name.stderr and $testfile_name.stderr.ref"
		exit 8
	fi
fi

# Executed program stdout file test
if [ -r $testfile_name.stdout.ref ]
then
	if [ ! -r $testfile_name.stdout ]
	then
		echo "$0: test_error: Cannot found file: $testfile_name.stdout"
		exit 9
	fi
	diff --strip-trailing-cr $testfile_name.stdout $testfile_name.stdout.ref &> /dev/null
	diff_stdout_exit_code=$?
	if [ $diff_stdout_exit_code -eq 0 ]
	then
		# echo "$0: message: Testcase for stdout passed. Cool. ;-)"
		rm -f $testfile_name.stderr
		rm -f $testfile_name.stdout
	elif [ $diff_stdout_exit_code -eq 1 ]
	then
		echo "$0: test_error: Files: $testfile_name.stdout and $testfile_name.stdout.ref differ"
		exit 10
	else
		echo "$0: internal_error: There is something wrong with the diff command and files: $testfile_name.stdout and $testfile_name.stdout.ref"
		exit 11
	fi
fi

exit 0
